import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import AuthProvider from "../providers/AuthProvider";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import ClientThemeWrapper from "@/providers/ClientThemeWrapper";
import { ThemeProvider } from "@/providers/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "create next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ClientThemeWrapper>
            <ReactQueryProvider>
              <AuthProvider>
                <NavBar />
                {children}
              </AuthProvider>
            </ReactQueryProvider>
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}


